### ISSUE TITLE
ui is distorted in url and custom-input

### ISSUE THREAD

**Issue by anilkarela** [vinay-code7/CS50-project#3]
![image](https://github.com/vinay-code7/CS50-project/assets/59861940/d956d088-d6b8-4f49-9e06-0196828dc9f6)

**Comment by vinay-code7** [comment]
Hey thanks for giving the time to use the site.
But can you elaborate more on the issue?
I didn't understand what you mean by UI is distorted.

**Comment by anilkarela** [comment]
the ui of the custom-input field and the url ( vinaycode7.pyth...) does not look goot, because of the rounded in center it does not look that good.

**Comment by vinay-code7** [comment]
thanks for contributing, the issue has been fixed now
